name: selvi_report
services:
  backend:
    container_name: selvi_report_container
    image: mochrira/dev:latest
    volumes:
      - ./:/workspace/www
      - ../src:/workspace/src
    ports:
      - 8092:80