name: selvi_report
version: '3.0'
services:
  backend:
    container_name: selvi_report_container
    image: mochrira/php:7.4.33-apache
    volumes:
      - ./:/var/www/html
      - ../src:/var/www/src
    ports:
      - 8092:80